/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {Signer} from "ethers";
import {Provider, TransactionRequest} from "@ethersproject/providers";
import {Contract, ContractFactory, Overrides} from "@ethersproject/contracts";

import type {MockFactoryCreatedPool} from "../MockFactoryCreatedPool";

export class MockFactoryCreatedPool__factory extends ContractFactory {
  constructor(signer?: Signer) {
    super(_abi, _bytecode, signer);
  }

  deploy(overrides?: Overrides): Promise<MockFactoryCreatedPool> {
    return super.deploy(overrides || {}) as Promise<MockFactoryCreatedPool>;
  }
  getDeployTransaction(overrides?: Overrides): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MockFactoryCreatedPool {
    return super.attach(address) as MockFactoryCreatedPool;
  }
  connect(signer: Signer): MockFactoryCreatedPool__factory {
    return super.connect(signer) as MockFactoryCreatedPool__factory;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MockFactoryCreatedPool {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MockFactoryCreatedPool;
  }
}

const _abi = [
  {
    inputs: [],
    name: "getPoolId",
    outputs: [
      {
        internalType: "bytes32",
        name: "",
        type: "bytes32",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052348015600f57600080fd5b50608a8061001e6000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c806338fff2d014602d575b600080fd5b60336047565b604051603e9190604b565b60405180910390f35b3090565b9081526020019056fea2646970667358221220e3c4222d7736db5d2ba0033ed771744e4ea139ace8216e81c6b3bf77c001b54264736f6c63430007010033";
