/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import {BytesLike} from "@ethersproject/bytes";
import {Listener, Provider} from "@ethersproject/providers";
import {FunctionFragment, EventFragment, Result} from "@ethersproject/abi";

interface ZapYearnSharesInterface extends ethers.utils.Interface {
  functions: {
    "authorize(address)": FunctionFragment;
    "authorized(address)": FunctionFragment;
    "deauthorize(address)": FunctionFragment;
    "deprecate()": FunctionFragment;
    "isAuthorized(address)": FunctionFragment;
    "isFrozen()": FunctionFragment;
    "owner()": FunctionFragment;
    "setIsFrozen(bool)": FunctionFragment;
    "setOwner(address)": FunctionFragment;
    "zapSharesIn(address,address,uint256,uint256,address,uint256)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "authorize", values: [string]): string;
  encodeFunctionData(functionFragment: "authorized", values: [string]): string;
  encodeFunctionData(functionFragment: "deauthorize", values: [string]): string;
  encodeFunctionData(functionFragment: "deprecate", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "isAuthorized",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "isFrozen", values?: undefined): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setIsFrozen",
    values: [boolean]
  ): string;
  encodeFunctionData(functionFragment: "setOwner", values: [string]): string;
  encodeFunctionData(
    functionFragment: "zapSharesIn",
    values: [string, string, BigNumberish, BigNumberish, string, BigNumberish]
  ): string;

  decodeFunctionResult(functionFragment: "authorize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "authorized", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deauthorize",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "deprecate", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "isAuthorized",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIsFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setOwner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "zapSharesIn",
    data: BytesLike
  ): Result;

  events: {};
}

export class ZapYearnShares extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ZapYearnSharesInterface;

  functions: {
    authorize(who: string, overrides?: Overrides): Promise<ContractTransaction>;

    "authorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<[boolean]>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    deauthorize(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "deauthorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    deprecate(overrides?: Overrides): Promise<ContractTransaction>;

    "deprecate()"(overrides?: Overrides): Promise<ContractTransaction>;

    isAuthorized(who: string, overrides?: CallOverrides): Promise<[boolean]>;

    "isAuthorized(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<[boolean]>;

    isFrozen(overrides?: CallOverrides): Promise<[boolean]>;

    "isFrozen()"(overrides?: CallOverrides): Promise<[boolean]>;

    owner(overrides?: CallOverrides): Promise<[string]>;

    "owner()"(overrides?: CallOverrides): Promise<[string]>;

    setIsFrozen(
      _newState: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "setIsFrozen(bool)"(
      _newState: boolean,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    setOwner(who: string, overrides?: Overrides): Promise<ContractTransaction>;

    "setOwner(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    zapSharesIn(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "zapSharesIn(address,address,uint256,uint256,address,uint256)"(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  authorize(who: string, overrides?: Overrides): Promise<ContractTransaction>;

  "authorize(address)"(
    who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

  "authorized(address)"(
    arg0: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  deauthorize(who: string, overrides?: Overrides): Promise<ContractTransaction>;

  "deauthorize(address)"(
    who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  deprecate(overrides?: Overrides): Promise<ContractTransaction>;

  "deprecate()"(overrides?: Overrides): Promise<ContractTransaction>;

  isAuthorized(who: string, overrides?: CallOverrides): Promise<boolean>;

  "isAuthorized(address)"(
    who: string,
    overrides?: CallOverrides
  ): Promise<boolean>;

  isFrozen(overrides?: CallOverrides): Promise<boolean>;

  "isFrozen()"(overrides?: CallOverrides): Promise<boolean>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  setIsFrozen(
    _newState: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "setIsFrozen(bool)"(
    _newState: boolean,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  setOwner(who: string, overrides?: Overrides): Promise<ContractTransaction>;

  "setOwner(address)"(
    who: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  zapSharesIn(
    _underlying: string,
    _vault: string,
    _amount: BigNumberish,
    _expiration: BigNumberish,
    _position: string,
    _ptExpected: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "zapSharesIn(address,address,uint256,uint256,address,uint256)"(
    _underlying: string,
    _vault: string,
    _amount: BigNumberish,
    _expiration: BigNumberish,
    _position: string,
    _ptExpected: BigNumberish,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    authorize(who: string, overrides?: CallOverrides): Promise<void>;

    "authorize(address)"(who: string, overrides?: CallOverrides): Promise<void>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<boolean>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    deauthorize(who: string, overrides?: CallOverrides): Promise<void>;

    "deauthorize(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<void>;

    deprecate(overrides?: CallOverrides): Promise<void>;

    "deprecate()"(overrides?: CallOverrides): Promise<void>;

    isAuthorized(who: string, overrides?: CallOverrides): Promise<boolean>;

    "isAuthorized(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<boolean>;

    isFrozen(overrides?: CallOverrides): Promise<boolean>;

    "isFrozen()"(overrides?: CallOverrides): Promise<boolean>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    setIsFrozen(_newState: boolean, overrides?: CallOverrides): Promise<void>;

    "setIsFrozen(bool)"(
      _newState: boolean,
      overrides?: CallOverrides
    ): Promise<void>;

    setOwner(who: string, overrides?: CallOverrides): Promise<void>;

    "setOwner(address)"(who: string, overrides?: CallOverrides): Promise<void>;

    zapSharesIn(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;

    "zapSharesIn(address,address,uint256,uint256,address,uint256)"(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: CallOverrides
    ): Promise<[BigNumber, BigNumber]>;
  };

  filters: {};

  estimateGas: {
    authorize(who: string, overrides?: Overrides): Promise<BigNumber>;

    "authorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    authorized(arg0: string, overrides?: CallOverrides): Promise<BigNumber>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    deauthorize(who: string, overrides?: Overrides): Promise<BigNumber>;

    "deauthorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    deprecate(overrides?: Overrides): Promise<BigNumber>;

    "deprecate()"(overrides?: Overrides): Promise<BigNumber>;

    isAuthorized(who: string, overrides?: CallOverrides): Promise<BigNumber>;

    "isAuthorized(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    isFrozen(overrides?: CallOverrides): Promise<BigNumber>;

    "isFrozen()"(overrides?: CallOverrides): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    setIsFrozen(_newState: boolean, overrides?: Overrides): Promise<BigNumber>;

    "setIsFrozen(bool)"(
      _newState: boolean,
      overrides?: Overrides
    ): Promise<BigNumber>;

    setOwner(who: string, overrides?: Overrides): Promise<BigNumber>;

    "setOwner(address)"(who: string, overrides?: Overrides): Promise<BigNumber>;

    zapSharesIn(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "zapSharesIn(address,address,uint256,uint256,address,uint256)"(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    authorize(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "authorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    authorized(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "authorized(address)"(
      arg0: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    deauthorize(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "deauthorize(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    deprecate(overrides?: Overrides): Promise<PopulatedTransaction>;

    "deprecate()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    isAuthorized(
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "isAuthorized(address)"(
      who: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    isFrozen(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "isFrozen()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    setIsFrozen(
      _newState: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "setIsFrozen(bool)"(
      _newState: boolean,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    setOwner(who: string, overrides?: Overrides): Promise<PopulatedTransaction>;

    "setOwner(address)"(
      who: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    zapSharesIn(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "zapSharesIn(address,address,uint256,uint256,address,uint256)"(
      _underlying: string,
      _vault: string,
      _amount: BigNumberish,
      _expiration: BigNumberish,
      _position: string,
      _ptExpected: BigNumberish,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
