name: Publish Package to npmjs

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      ALCHEMY_MUMBAI_API_KEY: ${{ secrets.ALCHEMY_MUMBAI_API_KEY }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.x'
          registry-url: 'https://registry.npmjs.org'
      - run: npm ci
      - run: npm run build-mumbai
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist/
      - name: Publish to NPM
        run: npm publish --access public